### ISSUE TITLE
When will be Admin Panel? and plans for upcoming future

### ISSUE THREAD

**Issue by koreos** [flextype/flextype#16]
When we can see admin panel? :-)

**Comment by Awilum** [comment]
Hello @koreos 
Here is a plans for May:
5 May - Flextype 0.3.0 release
6 - 9 May - website and plugins updates
21 May - Flextype 0.4.0 + First public version of Admin panel

**Comment by koreos** [comment]
Thank you Sergey.

**Comment by koreos** [comment]
"21 May - Flextype 0.4.0 + First public version of Admin panel"

21 May was 8 days ego.. :-)

**Comment by koreos** [comment]
That is right!

**Comment by AndiLeni** [comment]
Is there any update for this project? 
A first public alpha would be nice to see where it's going.

**Comment by Mu9tafa-Online** [comment]
@AndiLeni - Yes, the project is active, last commit was  days ago.

**Comment by AndiLeni** [comment]
I wanted to know how the work on the admin panel is going on. I'm aware that the main project is in active development.

**Comment by Awilum** [comment]
**Flextype is in active development!**
A lot of changes commiting almost every day and new plugins releasing!

Flextype Common Organization: https://github.com/flextype
Flextype Plugins: https://github.com/flextype-plugins
Flextype Components: https://github.com/flextype-components

**Focus for June (at least) is:**
- Flextype Core improvements and updates!
- Flxtype Plugins. A lot of simple plugins will be created for Flextype, to create a good plugins repository and while developing this plugins - each plugins helps to define strong and wekness parts of Flextype CMS, what should be improved and what should be removed from core.
- Flextype Documentaion. It is another very important part of the project, because now there is lack of documetations for users and developers. 

So as you can see, main priority of June it is: Core, Plugins and Documentation.

Primary Goal at the moment is invole developers (contributures) as much as possible into the project. 

I will able to get back to Admin Plugin development when other important things will be good enough.

**Comment by Awilum** [comment]
**If you want to create any useful plugin, and don't have any ideas what plugin to create, just go to WP plugins repository, check it and create same plugin for Flextype - it is easy.**

https://wordpress.org/plugins/

**Comment by koreos** [comment]
But why not admin panel first?

**Comment by Awilum** [comment]
Admin panel plugin - work in progress
![2018-06-25 16 09 34](https://user-images.githubusercontent.com/477114/41852018-90026554-7892-11e8-9b12-3cd5fcdb14dc.png)
![2018-06-25 16 09 11](https://user-images.githubusercontent.com/477114/41852019-9036dbae-7892-11e8-9bac-acec8a2f9c31.png)

**Comment by koreos** [comment]
Great! Please add TinyMCE.

**Comment by koreos** [comment]
Keywords field is not needed because Google doesn't use it.

**Comment by koreos** [comment]
Description field should be bigger like in Monstra. Right sidebar is not good idea in my opinion - in Monstra is perfect admin panel!

**Comment by Awilum** [comment]
![admin-panel-2018-06-25-16 44 05](https://user-images.githubusercontent.com/477114/41853928-aa7d353a-7897-11e8-8b57-00efa6873cdf.gif)

**Comment by Mu9tafa-Online** [comment]
is Admin Panel based on "**Bootstrap 4**" ?

**Comment by Awilum** [comment]
@Mu9tafa-Online Yes it is

**Comment by Awilum** [comment]
Admin Panel - 27.06.2018

![2018-06-27 3 34 34](https://user-images.githubusercontent.com/477114/41948717-b513cb8c-79c6-11e8-9557-0395f402d3c4.png)
![2018-06-27 3 34 24](https://user-images.githubusercontent.com/477114/41948720-b53377fc-79c6-11e8-9741-3d7b5dad1659.png)
![2018-06-27 3 35 43](https://user-images.githubusercontent.com/477114/41948716-b4f63838-79c6-11e8-9e0e-375dc12ec9f5.png)

**Comment by Awilum** [comment]
Admin Panel - 27.06.2018 - short video review 

![video-2018-06-27-15 14 18](https://user-images.githubusercontent.com/477114/41973519-e20470d6-7a1d-11e8-8e6b-d36443eaa5ae.gif)

**Comment by pascoal-sistemas** [comment]
Already in September and no admin panel!

This project without admin is somewhat ridiculous !!

The differential would be a panel to manage every site and post, no panel becomes bad !!

Who will use this system ??? At the moment we have 1000x better web systems!

The most important is the panel !!!!!!!!!!!!!

Without panel this project becomes a crap with no logic of use !!

**Comment by Awilum** [comment]
Done
